/*
 * Copyright (c) 2012-2013 Bruno Barbieri
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list
 * of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

package io.github.brunorex;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MkvStrings {

    /*
     * ISO639 language names and codes
     * Taken from iso639.cpp, part of mkvtoolnix by Moritz Bunkus
     *
     */
    private String[] langNames = {
            "Abkhazian",
            "Achinese",
            "Acoli",
            "Adangme",
            "Adyghe; Adygei",
            "Afar",
            "Afrihili",
            "Afrikaans",
            "Afro-Asiatic languages",
            "Ainu",
            "Akan",
            "Akkadian",
            "Albanian",
            "Aleut",
            "Algonquian languages",
            "Altaic languages",
            "Amharic",
            "Angika",
            "Apache languages",
            "Arabic",
            "Aragonese",
            "Arapaho",
            "Arawak",
            "Armenian",
            "Aromanian; Arumanian; Macedo-Romanian",
            "Artificial languages",
            "Assamese",
            "Asturian; Bable; Leonese; Asturleonese",
            "Athapascan languages",
            "Australian languages",
            "Austronesian languages",
            "Avaric",
            "Avestan",
            "Awadhi",
            "Aymara",
            "Azerbaijani",
            "Balinese",
            "Baltic languages",
            "Baluchi",
            "Bambara",
            "Bamileke languages",
            "Banda languages",
            "Bantu (Other)",
            "Basa",
            "Bashkir",
            "Basque",
            "Batak languages",
            "Beja; Bedawiyet",
            "Belarusian",
            "Bemba",
            "Bengali",
            "Berber languages",
            "Bhojpuri",
            "Bihari languages",
            "Bikol",
            "Bini; Edo",
            "Bislama",
            "Blin; Bilin",
            "Blissymbols; Blissymbolics; Bliss",
            "Bokmål, Norwegian; Norwegian Bokmål",
            "Bosnian",
            "Braj",
            "Breton",
            "Buginese",
            "Bulgarian",
            "Buriat",
            "Burmese",
            "Caddo",
            "Catalan; Valencian",
            "Caucasian languages",
            "Cebuano",
            "Celtic languages",
            "Central American Indian languages",
            "Central Khmer",
            "Chagatai",
            "Chamic languages",
            "Chamorro",
            "Chechen",
            "Cherokee",
            "Cheyenne",
            "Chibcha",
            "Chichewa; Chewa; Nyanja",
            "Chinese",
            "Chinook jargon",
            "Chipewyan; Dene Suline",
            "Choctaw",
            "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
            "Chuukese",
            "Chuvash",
            "Classical Newari; Old Newari; Classical Nepal Bhasa",
            "Classical Syriac",
            "Coptic",
            "Cornish",
            "Corsican",
            "Cree",
            "Creek",
            "Creoles and pidgins",
            "Creoles and pidgins, English based",
            "Creoles and pidgins, French-based",
            "Creoles and pidgins, Portuguese-based",
            "Crimean Tatar; Crimean Turkish",
            "Croatian",
            "Cushitic languages",
            "Czech",
            "Dakota",
            "Danish",
            "Dargwa",
            "Delaware",
            "Dinka",
            "Divehi; Dhivehi; Maldivian",
            "Dogri",
            "Dogrib",
            "Dravidian languages",
            "Duala",
            "Dutch, Middle (ca.1050-1350)",
            "Dutch; Flemish",
            "Dyula",
            "Dzongkha",
            "Eastern Frisian",
            "Efik",
            "Egyptian (Ancient)",
            "Ekajuk",
            "Elamite",
            "English",
            "English, Middle (1100-1500)",
            "English, Old (ca.450-1100)",
            "Erzya",
            "Esperanto",
            "Estonian",
            "Ewe",
            "Ewondo",
            "Fang",
            "Fanti",
            "Faroese",
            "Fijian",
            "Filipino; Pilipino",
            "Finnish",
            "Finno-Ugrian languages",
            "Fon",
            "French",
            "French, Middle (ca.1400-1600)",
            "French, Old (842-ca.1400)",
            "Friulian",
            "Fulah",
            "Ga",
            "Gaelic; Scottish Gaelic",
            "Galibi Carib",
            "Galician",
            "Ganda",
            "Gayo",
            "Gbaya",
            "Geez",
            "Georgian",
            "German",
            "German, Middle High (ca.1050-1500)",
            "German, Old High (ca.750-1050)",
            "Germanic languages",
            "Gilbertese",
            "Gondi",
            "Gorontalo",
            "Gothic",
            "Grebo",
            "Greek, Ancient (to 1453)",
            "Greek, Modern (1453-)",
            "Guarani",
            "Gujarati",
            "Gwich'in",
            "Haida",
            "Haitian; Haitian Creole",
            "Hausa",
            "Hawaiian",
            "Hebrew",
            "Herero",
            "Hiligaynon",
            "Himachali languages; Western Pahari languages",
            "Hindi",
            "Hiri Motu",
            "Hittite",
            "Hmong; Mong",
            "Hungarian",
            "Hupa",
            "Iban",
            "Icelandic",
            "Ido",
            "Igbo",
            "Ijo languages",
            "Iloko",
            "Inari Sami",
            "Indic languages",
            "Indo-European languages",
            "Indonesian",
            "Ingush",
            "Interlingua (International Auxiliary Language Association)",
            "Interlingue; Occidental",
            "Inuktitut",
            "Inupiaq",
            "Iranian languages",
            "Irish",
            "Irish, Middle (900-1200)",
            "Irish, Old (to 900)",
            "Iroquoian languages",
            "Italian",
            "Japanese",
            "Javanese",
            "Judeo-Arabic",
            "Judeo-Persian",
            "Kabardian",
            "Kabyle",
            "Kachin; Jingpho",
            "Kalaallisut; Greenlandic",
            "Kalmyk; Oirat",
            "Kamba",
            "Kannada",
            "Kanuri",
            "Kara-Kalpak",
            "Karachay-Balkar",
            "Karelian",
            "Karen languages",
            "Kashmiri",
            "Kashubian",
            "Kawi",
            "Kazakh",
            "Khasi",
            "Khoisan languages",
            "Khotanese; Sakan",
            "Kikuyu; Gikuyu",
            "Kimbundu",
            "Kinyarwanda",
            "Kirghiz; Kyrgyz",
            "Klingon; tlhIngan-Hol",
            "Komi",
            "Kongo",
            "Konkani",
            "Korean",
            "Kosraean",
            "Kpelle",
            "Kru languages",
            "Kuanyama; Kwanyama",
            "Kumyk",
            "Kurdish",
            "Kurukh",
            "Kutenai",
            "Ladino",
            "Lahnda",
            "Lamba",
            "Land Dayak languages",
            "Lao",
            "Latin",
            "Latvian",
            "Lezghian",
            "Limburgan; Limburger; Limburgish",
            "Lingala",
            "Lithuanian",
            "Lojban",
            "Low German; Low Saxon; German, Low; Saxon, Low",
            "Lower Sorbian",
            "Lozi",
            "Luba-Katanga",
            "Luba-Lulua",
            "Luiseno",
            "Lule Sami",
            "Lunda",
            "Luo (Kenya and Tanzania)",
            "Lushai",
            "Luxembourgish; Letzeburgesch",
            "Macedonian",
            "Madurese",
            "Magahi",
            "Maithili",
            "Makasar",
            "Malagasy",
            "Malay",
            "Malayalam",
            "Maltese",
            "Manchu",
            "Mandar",
            "Mandingo",
            "Manipuri",
            "Manobo languages",
            "Manx",
            "Maori",
            "Mapudungun; Mapuche",
            "Marathi",
            "Mari",
            "Marshallese",
            "Marwari",
            "Masai",
            "Mayan languages",
            "Mende",
            "Mi'kmaq; Micmac",
            "Minangkabau",
            "Mirandese",
            "Mohawk",
            "Moksha",
            "Mon-Khmer languages",
            "Mongo",
            "Mongolian",
            "Mossi",
            "Multiple languages",
            "Munda languages",
            "N'Ko",
            "Nahuatl languages",
            "Nauru",
            "Navajo; Navaho",
            "Ndebele, North; North Ndebele",
            "Ndebele, South; South Ndebele",
            "Ndonga",
            "Neapolitan",
            "Nepal Bhasa; Newari",
            "Nepali",
            "Nias",
            "Niger-Kordofanian languages",
            "Nilo-Saharan languages",
            "Niuean",
            "No linguistic content; Not applicable",
            "Nogai",
            "Norse, Old",
            "North American Indian languages",
            "Northern Frisian",
            "Northern Sami",
            "Norwegian Nynorsk; Nynorsk, Norwegian",
            "Norwegian",
            "Nubian languages",
            "Nyamwezi",
            "Nyankole",
            "Nyoro",
            "Nzima",
            "Occitan (post 1500)",
            "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
            "Ojibwa",
            "Oriya",
            "Oromo",
            "Osage",
            "Ossetian; Ossetic",
            "Otomian languages",
            "Pahlavi",
            "Palauan",
            "Pali",
            "Pampanga; Kapampangan",
            "Pangasinan",
            "Panjabi; Punjabi",
            "Papiamento",
            "Papuan languages",
            "Pedi; Sepedi; Northern Sotho",
            "Persian",
            "Persian, Old (ca.600-400 B.C.)",
            "Philippine languages",
            "Phoenician",
            "Pohnpeian",
            "Polish",
            "Portuguese",
            "Prakrit languages",
            "Provençal, Old (to 1500);Occitan, Old (to 1500)",
            "Pushto; Pashto",
            "Quechua",
            "Rajasthani",
            "Rapanui",
            "Rarotongan; Cook Islands Maori",
            "Romance languages",
            "Romanian; Moldavian; Moldovan",
            "Romansh",
            "Romany",
            "Rundi",
            "Russian",
            "Salishan languages",
            "Samaritan Aramaic",
            "Sami languages",
            "Samoan",
            "Sandawe",
            "Sango",
            "Sanskrit",
            "Santali",
            "Sardinian",
            "Sasak",
            "Scots",
            "Selkup",
            "Semitic languages",
            "Serbian",
            "Serer",
            "Shan",
            "Shona",
            "Sichuan Yi; Nuosu",
            "Sicilian",
            "Sidamo",
            "Sign Languages",
            "Siksika",
            "Sindhi",
            "Sinhala; Sinhalese",
            "Sino-Tibetan languages",
            "Siouan languages",
            "Skolt Sami",
            "Slave (Athapascan)",
            "Slavic languages",
            "Slovak",
            "Slovenian",
            "Sogdian",
            "Somali",
            "Songhai languages",
            "Soninke",
            "Sorbian languages",
            "Sotho, Southern",
            "South American Indian (Other)",
            "Southern Altai",
            "Southern Sami",
            "Spanish; Castillan",
            "Sranan Tongo",
            "Sukuma",
            "Sumerian",
            "Sundanese",
            "Susu",
            "Swahili",
            "Swati",
            "Swedish",
            "Swiss German; Alemannic; Alsatian",
            "Syriac",
            "Tagalog",
            "Tahitian",
            "Tai languages",
            "Tajik",
            "Tamashek",
            "Tamil",
            "Tatar",
            "Telugu",
            "Tereno",
            "Tetum",
            "Thai",
            "Tibetan",
            "Tigre",
            "Tigrinya",
            "Timne",
            "Tiv",
            "Tlingit",
            "Tok Pisin",
            "Tokelau",
            "Tonga (Nyasa)",
            "Tonga (Tonga Islands)",
            "Tsimshian",
            "Tsonga",
            "Tswana",
            "Tumbuka",
            "Tupi languages",
            "Turkish",
            "Turkish, Ottoman (1500-1928)",
            "Turkmen",
            "Tuvalu",
            "Tuvinian",
            "Twi",
            "Udmurt",
            "Ugaritic",
            "Uighur; Uyghur",
            "Ukrainian",
            "Umbundu",
            "Uncoded languages",
            "Undetermined",
            "Upper Sorbian",
            "Urdu",
            "Uzbek",
            "Vai",
            "Venda",
            "Vietnamese",
            "Volapük",
            "Votic",
            "Wakashan languages",
            "Walamo",
            "Walloon",
            "Waray",
            "Washo",
            "Welsh",
            "Western Frisian",
            "Wolof",
            "Xhosa",
            "Yakut",
            "Yao",
            "Yapese",
            "Yiddish",
            "Yoruba",
            "Yupik languages",
            "Zande languages",
            "Zapotec",
            "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
            "Zenaga",
            "Zhuang; Chuang",
            "Zulu",
            "Zuni"
    };

    private String[] langCodes = {
            "abk",
            "ace",
            "ach",
            "ada",
            "ady",
            "aar",
            "afh",
            "afr",
            "afa",
            "ain",
            "aka",
            "akk",
            "alb",
            "ale",
            "alg",
            "tut",
            "amh",
            "anp",
            "apa",
            "ara",
            "arg",
            "arp",
            "arw",
            "arm",
            "rup",
            "art",
            "asm",
            "ast",
            "ath",
            "aus",
            "map",
            "ava",
            "ave",
            "awa",
            "aym",
            "aze",
            "ban",
            "bat",
            "bal",
            "bam",
            "bai",
            "bad",
            "bnt",
            "bas",
            "bak",
            "baq",
            "btk",
            "bej",
            "bel",
            "bem",
            "ben",
            "ber",
            "bho",
            "bih",
            "bik",
            "bin",
            "bis",
            "byn",
            "zbl",
            "nob",
            "bos",
            "bra",
            "bre",
            "bug",
            "bul",
            "bua",
            "bur",
            "cad",
            "cat",
            "cau",
            "ceb",
            "cel",
            "cai",
            "khm",
            "chg",
            "cmc",
            "cha",
            "che",
            "chr",
            "chy",
            "chb",
            "nya",
            "chi",
            "chn",
            "chp",
            "cho",
            "chu",
            "chk",
            "chv",
            "nwc",
            "syc",
            "cop",
            "cor",
            "cos",
            "cre",
            "mus",
            "crp",
            "cpe",
            "cpf",
            "cpp",
            "crh",
            "hrv",
            "cus",
            "cze",
            "dak",
            "dan",
            "dar",
            "del",
            "din",
            "div",
            "doi",
            "dgr",
            "dra",
            "dua",
            "dum",
            "dut",
            "dyu",
            "dzo",
            "frs",
            "efi",
            "egy",
            "eka",
            "elx",
            "eng",
            "enm",
            "ang",
            "myv",
            "epo",
            "est",
            "ewe",
            "ewo",
            "fan",
            "fat",
            "fao",
            "fij",
            "fil",
            "fin",
            "fiu",
            "fon",
            "fre",
            "frm",
            "fro",
            "fur",
            "ful",
            "gaa",
            "gla",
            "car",
            "glg",
            "lug",
            "gay",
            "gba",
            "gez",
            "geo",
            "ger",
            "gmh",
            "goh",
            "gem",
            "gil",
            "gon",
            "gor",
            "got",
            "grb",
            "grc",
            "gre",
            "grn",
            "guj",
            "gwi",
            "hai",
            "hat",
            "hau",
            "haw",
            "heb",
            "her",
            "hil",
            "him",
            "hin",
            "hmo",
            "hit",
            "hmn",
            "hun",
            "hup",
            "iba",
            "ice",
            "ido",
            "ibo",
            "ijo",
            "ilo",
            "smn",
            "inc",
            "ine",
            "ind",
            "inh",
            "ina",
            "ile",
            "iku",
            "ipk",
            "ira",
            "gle",
            "mga",
            "sga",
            "iro",
            "ita",
            "jpn",
            "jav",
            "jrb",
            "jpr",
            "kbd",
            "kab",
            "kac",
            "kal",
            "xal",
            "kam",
            "kan",
            "kau",
            "kaa",
            "krc",
            "krl",
            "kar",
            "kas",
            "csb",
            "kaw",
            "kaz",
            "kha",
            "khi",
            "kho",
            "kik",
            "kmb",
            "kin",
            "kir",
            "tlh",
            "kom",
            "kon",
            "kok",
            "kor",
            "kos",
            "kpe",
            "kro",
            "kua",
            "kum",
            "kur",
            "kru",
            "kut",
            "lad",
            "lah",
            "lam",
            "day",
            "lao",
            "lat",
            "lav",
            "lez",
            "lim",
            "lin",
            "lit",
            "jbo",
            "nds",
            "dsb",
            "loz",
            "lub",
            "lua",
            "lui",
            "smj",
            "lun",
            "luo",
            "lus",
            "ltz",
            "mac",
            "mad",
            "mag",
            "mai",
            "mak",
            "mlg",
            "may",
            "mal",
            "mlt",
            "mnc",
            "mdr",
            "man",
            "mni",
            "mno",
            "glv",
            "mao",
            "arn",
            "mar",
            "chm",
            "mah",
            "mwr",
            "mas",
            "myn",
            "men",
            "mic",
            "min",
            "mwl",
            "moh",
            "mdf",
            "mkh",
            "lol",
            "mon",
            "mos",
            "mul",
            "mun",
            "nqo",
            "nah",
            "nau",
            "nav",
            "nde",
            "nbl",
            "ndo",
            "nap",
            "new",
            "nep",
            "nia",
            "nic",
            "ssa",
            "niu",
            "zxx",
            "nog",
            "non",
            "nai",
            "frr",
            "sme",
            "nno",
            "nor",
            "nub",
            "nym",
            "nyn",
            "nyo",
            "nzi",
            "oci",
            "arc",
            "oji",
            "ori",
            "orm",
            "osa",
            "oss",
            "oto",
            "pal",
            "pau",
            "pli",
            "pam",
            "pag",
            "pan",
            "pap",
            "paa",
            "nso",
            "per",
            "peo",
            "phi",
            "phn",
            "pon",
            "pol",
            "por",
            "pra",
            "pro",
            "pus",
            "que",
            "raj",
            "rap",
            "rar",
            "roa",
            "rum",
            "roh",
            "rom",
            "run",
            "rus",
            "sal",
            "sam",
            "smi",
            "smo",
            "sad",
            "sag",
            "san",
            "sat",
            "srd",
            "sas",
            "sco",
            "sel",
            "sem",
            "srp",
            "srr",
            "shn",
            "sna",
            "iii",
            "scn",
            "sid",
            "sgn",
            "bla",
            "snd",
            "sin",
            "sit",
            "sio",
            "sms",
            "den",
            "sla",
            "slo",
            "slv",
            "sog",
            "som",
            "son",
            "snk",
            "wen",
            "sot",
            "sai",
            "alt",
            "sma",
            "spa",
            "srn",
            "suk",
            "sux",
            "sun",
            "sus",
            "swa",
            "ssw",
            "swe",
            "gsw",
            "syr",
            "tgl",
            "tah",
            "tai",
            "tgk",
            "tmh",
            "tam",
            "tat",
            "tel",
            "ter",
            "tet",
            "tha",
            "tib",
            "tig",
            "tir",
            "tem",
            "tiv",
            "tli",
            "tpi",
            "tkl",
            "tog",
            "ton",
            "tsi",
            "tso",
            "tsn",
            "tum",
            "tup",
            "tur",
            "ota",
            "tuk",
            "tvl",
            "tyv",
            "twi",
            "udm",
            "uga",
            "uig",
            "ukr",
            "umb",
            "mis",
            "und",
            "hsb",
            "urd",
            "uzb",
            "vai",
            "ven",
            "vie",
            "vol",
            "vot",
            "wak",
            "wal",
            "wln",
            "war",
            "was",
            "wel",
            "fry",
            "wol",
            "xho",
            "sah",
            "yao",
            "yap",
            "yid",
            "yor",
            "ypk",
            "znd",
            "zap",
            "zza",
            "zen",
            "zha",
            "zul",
            "zun"
    };

    /*
     * Matroska MIME Types
     * Taken from extern_data.cpp, part of mkvtoolnix by Moritz Bunkus
     *
     */
    private String[] mimeTypes = {
            "",
            "application/activemessage",
            "application/andrew-inset",
            "application/applefile",
            "application/atomicmail",
            "application/batch-SMTP",
            "application/beep+xml",
            "application/cals-1840",
            "application/commonground",
            "application/cu-seeme",
            "application/cybercash",
            "application/dca-rft",
            "application/dec-dx",
            "application/dsptype",
            "application/dvcs",
            "application/edi-consent",
            "application/EDI-Consent",
            "application/edifact",
            "application/EDIFACT",
            "application/edi-x12",
            "application/EDI-X12",
            "application/eshop",
            "application/font-tdpfr",
            "application/futuresplash",
            "application/ghostview",
            "application/hta",
            "application/http",
            "application/hyperstudio",
            "application/iges",
            "application/index",
            "application/index.cmd",
            "application/index.obj",
            "application/index.response",
            "application/index.vnd",
            "application/iotp",
            "application/ipp",
            "application/isup",
            "application/mac-binhex40",
            "application/mac-compactpro",
            "application/macwriteii",
            "application/marc",
            "application/mathematica",
            "application/mathematica-old",
            "application/msaccess",
            "application/msword",
            "application/news-message-id",
            "application/news-transmission",
            "application/ocsp-request",
            "application/ocsp-response",
            "application/octet-stream",
            "application/oda",
            "application/parityfec",
            "application/pdf",
            "application/pgp-encrypted",
            "application/pgp-keys",
            "application/pgp-signature",
            "application/pics-rules",
            "application/pkcs10",
            "application/pkcs7-mime",
            "application/pkcs7-signature",
            "application/pkix-cert",
            "application/pkixcmp",
            "application/pkix-crl",
            "application/postscript",
            "application/prs.alvestrand.titrax-sheet",
            "application/prs.cww",
            "application/prs.nprend",
            "application/qsig",
            "application/remote-printing",
            "application/riscos",
            "application/rtf",
            "application/sdp",
            "application/set-payment",
            "application/set-payment-initiation",
            "application/set-registration",
            "application/set-registration-initiation",
            "application/sgml",
            "application/sgml-open-catalog",
            "application/sieve",
            "application/slate",
            "application/smil",
            "application/timestamp-query",
            "application/timestamp-reply",
            "application/vemmi",
            "application/vnd.3M.Post-it-Notes",
            "application/vnd.accpac.simply.aso",
            "application/vnd.accpac.simply.imp",
            "application/vnd.acucobol",
            "application/vnd.aether.imp",
            "application/vnd.anser-web-certificate-issue-initiation",
            "application/vnd.anser-web-funds-transfer-initiation",
            "application/vnd.audiograph",
            "application/vnd.bmi",
            "application/vnd.businessobjects",
            "application/vnd.canon-cpdl",
            "application/vnd.canon-lips",
            "application/vnd.cinderella",
            "application/vnd.claymore",
            "application/vnd.$commerce_battelle",
            "application/vnd.commerce-battelle",
            "application/vnd.commonspace",
            "application/vnd.comsocaller",
            "application/vnd.contact.cmsg",
            "application/vnd.cosmocaller",
            "application/vnd.ctc-posml",
            "application/vnd.cups-postscript",
            "application/vnd.cups-raster",
            "application/vnd.cups-raw",
            "application/vnd.cybank",
            "application/vnd.dna",
            "application/vnd.dpgraph",
            "application/vnd.dxr",
            "application/vnd.ecdis-update",
            "application/vnd.ecowin.chart",
            "application/vnd.ecowin.filerequest",
            "application/vnd.ecowin.fileupdate",
            "application/vnd.ecowin.series",
            "application/vnd.ecowin.seriesrequest",
            "application/vnd.ecowin.seriesupdate",
            "application/vnd.enliven",
            "application/vnd.epson.esf",
            "application/vnd.epson.msf",
            "application/vnd.epson.quickanime",
            "application/vnd.epson.salt",
            "application/vnd.epson.ssf",
            "application/vnd.ericsson.quickcall",
            "application/vnd.eudora.data",
            "application/vnd.fdf",
            "application/vnd.ffsns",
            "application/vnd.flographit",
            "application/vnd.FloGraphIt",
            "application/vnd.framemaker",
            "application/vnd.fsc.weblaunch",
            "application/vnd.fujitsu.oasys",
            "application/vnd.fujitsu.oasys2",
            "application/vnd.fujitsu.oasys3",
            "application/vnd.fujitsu.oasysgp",
            "application/vnd.fujitsu.oasysprs",
            "application/vnd.fujixerox.ddd",
            "application/vnd.fujixerox.docuworks",
            "application/vnd.fujixerox.docuworks.binder",
            "application/vnd.fut-misnet",
            "application/vnd.grafeq",
            "application/vnd.groove-account",
            "application/vnd.groove-identity-message",
            "application/vnd.groove-injector",
            "application/vnd.groove-tool-message",
            "application/vnd.groove-tool-template",
            "application/vnd.groove-vcard",
            "application/vnd.hhe.lesson-player",
            "application/vnd.hp-HPGL",
            "application/vnd.hp-hpid",
            "application/vnd.hp-hps",
            "application/vnd.hp-PCL",
            "application/vnd.hp-PCLXL",
            "application/vnd.httphone",
            "application/vnd.hzn-3d-crossword",
            "application/vnd.ibm.afplinedata",
            "application/vnd.ibm.MiniPay",
            "application/vnd.ibm.modcap",
            "application/vnd.informix-visionary",
            "application/vnd.intercon.formnet",
            "application/vnd.intertrust.digibox",
            "application/vnd.intertrust.nncp",
            "application/vnd.intu.qbo",
            "application/vnd.intu.qfx",
            "application/vnd.irepository.package+xml",
            "application/vnd.is-xpr",
            "application/vnd.japannet-directory-service",
            "application/vnd.japannet-jpnstore-wakeup",
            "application/vnd.japannet-payment-wakeup",
            "application/vnd.japannet-registration",
            "application/vnd.japannet-registration-wakeup",
            "application/vnd.japannet-setstore-wakeup",
            "application/vnd.japannet-verification",
            "application/vnd.japannet-verification-wakeup",
            "application/vnd.koan",
            "application/vnd.lotus-1-2-3",
            "application/vnd.lotus-approach",
            "application/vnd.lotus-freelance",
            "application/vnd.lotus-notes",
            "application/vnd.lotus-organizer",
            "application/vnd.lotus-screencam",
            "application/vnd.lotus-wordpro",
            "application/vnd.mcd",
            "application/vnd.mediastation.cdkey",
            "application/vnd.meridian-slingshot",
            "application/vnd.mif",
            "application/vnd.minisoft-hp3000-save",
            "application/vnd.mitsubishi.misty-guard.trustweb",
            "application/vnd.mobius.daf",
            "application/vnd.Mobius.DAF",
            "application/vnd.mobius.dis",
            "application/vnd.Mobius.DIS",
            "application/vnd.Mobius.MBK",
            "application/vnd.Mobius.MQY",
            "application/vnd.mobius.msl",
            "application/vnd.Mobius.MSL",
            "application/vnd.mobius.plc",
            "application/vnd.Mobius.PLC",
            "application/vnd.mobius.txf",
            "application/vnd.Mobius.TXF",
            "application/vnd.motorola.flexsuite",
            "application/vnd.motorola.flexsuite.adsi",
            "application/vnd.motorola.flexsuite.fis",
            "application/vnd.motorola.flexsuite.gotap",
            "application/vnd.motorola.flexsuite.kmr",
            "application/vnd.motorola.flexsuite.ttc",
            "application/vnd.motorola.flexsuite.wem",
            "application/vnd.mozilla.xul+xml",
            "application/vnd.ms-artgalry",
            "application/vnd.ms-asf",
            "application/vnd.mseq",
            "application/vnd.ms-excel",
            "application/vnd.msign",
            "application/vnd.ms-lrm",
            "application/vnd.ms-pki.seccat",
            "application/vnd.ms-pki.stl",
            "application/vnd.ms-powerpoint",
            "application/vnd.ms-project",
            "application/vnd.ms-tnef",
            "application/vnd.ms-works",
            "application/vnd.musician",
            "application/vnd.music-niff",
            "application/vnd.netfpx",
            "application/vnd.noblenet-directory",
            "application/vnd.noblenet-sealer",
            "application/vnd.noblenet-web",
            "application/vnd.novadigm.EDM",
            "application/vnd.novadigm.EDX",
            "application/vnd.novadigm.EXT",
            "application/vnd.osa.netdeploy",
            "application/vnd.palm",
            "application/vnd.pg.format",
            "application/vnd.pg.osasli",
            "application/vnd.powerbuilder6",
            "application/vnd.powerbuilder6-s",
            "application/vnd.powerbuilder7",
            "application/vnd.powerbuilder75",
            "application/vnd.powerbuilder75-s",
            "application/vnd.powerbuilder7-s",
            "application/vnd.previewsystems.box",
            "application/vnd.publishare-delta-tree",
            "application/vnd.pvi.ptid1",
            "application/vnd.pwg-xhtml-print+xml",
            "application/vnd.rapid",
            "application/vnd.s3sms",
            "application/vnd.seemail",
            "application/vnd.shana.informed.formdata",
            "application/vnd.shana.informed.formtemplate",
            "application/vnd.shana.informed.interchange",
            "application/vnd.shana.informed.package",
            "application/vnd.sss-cod",
            "application/vnd.sss-dtf",
            "application/vnd.sss-ntf",
            "application/vnd.stardivision.calc",
            "application/vnd.stardivision.draw",
            "application/vnd.stardivision.impress",
            "application/vnd.stardivision.math",
            "application/vnd.stardivision.writer",
            "application/vnd.stardivision.writer-global",
            "application/vnd.street-stream",
            "application/vnd.sun.xml.calc",
            "application/vnd.sun.xml.calc.template",
            "application/vnd.sun.xml.draw",
            "application/vnd.sun.xml.draw.template",
            "application/vnd.sun.xml.impress",
            "application/vnd.sun.xml.impress.template",
            "application/vnd.sun.xml.math",
            "application/vnd.sun.xml.writer",
            "application/vnd.sun.xml.writer.global",
            "application/vnd.sun.xml.writer.template",
            "application/vnd.svd",
            "application/vnd.swiftview-ics",
            "application/vnd.triscape.mxs",
            "application/vnd.trueapp",
            "application/vnd.truedoc",
            "application/vnd.tve-trigger",
            "application/vnd.ufdl",
            "application/vnd.uplanet.alert",
            "application/vnd.uplanet.alert-wbxml",
            "application/vnd.uplanet.bearer-choice",
            "application/vnd.uplanet.bearer-choice-wbxml",
            "application/vnd.uplanet.cacheop",
            "application/vnd.uplanet.cacheop-wbxml",
            "application/vnd.uplanet.channel",
            "application/vnd.uplanet.channel-wbxml",
            "application/vnd.uplanet.list",
            "application/vnd.uplanet.listcmd",
            "application/vnd.uplanet.listcmd-wbxml",
            "application/vnd.uplanet.list-wbxml",
            "application/vnd.uplanet.signal",
            "application/vnd.vcx",
            "application/vnd.vectorworks",
            "application/vnd.vidsoft.vidconference",
            "application/vnd.visio",
            "application/vnd.vividence.scriptfile",
            "application/vnd.wap.sic",
            "application/vnd.wap.slc",
            "application/vnd.wap.wbxml",
            "application/vnd.wap.wmlc",
            "application/vnd.wap.wmlscriptc",
            "application/vnd.webturbo",
            "application/vnd.wrq-hp3000-labelled",
            "application/vnd.wt.stf",
            "application/vnd.xara",
            "application/vnd.xfdl",
            "application/vnd.yellowriver-custom-menu",
            "application/whoispp-query",
            "application/whoispp-response",
            "application/wita",
            "application/wordperfect5.1",
            "application/x-123",
            "application/x400-bp",
            "application/x-bcpio",
            "application/x-cdf",
            "application/x-cdlink",
            "application/x-chess-pgn",
            "application/x-core",
            "application/x-cpio",
            "application/x-csh",
            "application/x-debian-package",
            "application/x-director",
            "application/x-dms",
            "application/x-doom",
            "application/x-dvi",
            "application/x-executable",
            "application/x-font",
            "application/x-futuresplash",
            "application/x-gnumeric",
            "application/x-graphing-calculator",
            "application/x-gtar",
            "application/x-hdf",
            "application/xhtml+xml",
            "application/x-httpd-php",
            "application/x-httpd-php3",
            "application/x-httpd-php3-preprocessed",
            "application/x-httpd-php4",
            "application/x-httpd-php-source",
            "application/x-ica",
            "application/x-internet-signup",
            "application/x-iphone",
            "application/x-java-applet",
            "application/x-java-archive",
            "application/x-java-bean",
            "application/x-java-jnlp-file",
            "application/x-javascript",
            "application/x-java-serialized-object",
            "application/x-java-vm",
            "application/x-kchart",
            "application/x-kdelnk",
            "application/x-killustrator",
            "application/x-koan",
            "application/x-kpresenter",
            "application/x-kspread",
            "application/x-kword",
            "application/x-latex",
            "application/x-lha",
            "application/x-lzh",
            "application/x-lzx",
            "application/x-maker",
            "application/x-mif",
            "application/xml",
            "application/xml-dtd",
            "application/xml-external-parsed-entity",
            "application/x-msdos-program",
            "application/x-msi",
            "application/x-ms-wmd",
            "application/x-ms-wmz",
            "application/x-netcdf",
            "application/x-ns-proxy-autoconfig",
            "application/x-object",
            "application/x-ogg",
            "application/x-oz-application",
            "application/x-perl",
            "application/x-pkcs7-certreqresp",
            "application/x-pkcs7-crl",
            "application/x-quicktimeplayer",
            "application/x-redhat-package-manager",
            "application/x-rx",
            "application/x-sh",
            "application/x-shar",
            "application/x-shellscript",
            "application/x-shockwave-flash",
            "application/x-stuffit",
            "application/x-sv4cpio",
            "application/x-sv4crc",
            "application/x-tar",
            "application/x-tcl",
            "application/x-tex",
            "application/x-tex-gf",
            "application/x-texinfo",
            "application/x-tex-pk",
            "application/x-trash",
            "application/x-troff",
            "application/x-troff-man",
            "application/x-troff-me",
            "application/x-troff-ms",
            "application/x-truetype-font",
            "application/x-ustar",
            "application/x-wais-source",
            "application/x-wingz",
            "application/x-x509-ca-cert",
            "application/x-xfig",
            "application/zip",
            "audio/32kadpcm",
            "audio/basic",
            "audio/DAT12",
            "audio/g.722.1",
            "audio/G.722.1",
            "audio/l16",
            "audio/L16",
            "audio/L20",
            "audio/L24",
            "audio/midi",
            "audio/mp4a-latm",
            "audio/MP4A-LATM",
            "audio/mpa-robust",
            "audio/mpeg",
            "audio/mpegurl",
            "audio/parityfec",
            "audio/prs.sid",
            "audio/telephone-event",
            "audio/tone",
            "audio/vnd.cisco.nse",
            "audio/vnd.cns.anp1",
            "audio/vnd.cns.inf1",
            "audio/vnd.digital-winds",
            "audio/vnd.everad.plj",
            "audio/vnd.lucent.voice",
            "audio/vnd.nortel.vbk",
            "audio/vnd.nuera.ecelp4800",
            "audio/vnd.nuera.ecelp7470",
            "audio/vnd.nuera.ecelp9600",
            "audio/vnd.octel.sbc",
            "audio/vnd.qcelp",
            "audio/vnd.rhetorex.32kadpcm",
            "audio/vnd.vmx.cvsd",
            "audio/x-aiff",
            "audio/x-gsm",
            "audio/x-mpegurl",
            "audio/x-ms-wax",
            "audio/x-ms-wma",
            "audio/x-pn-realaudio",
            "audio/x-pn-realaudio-plugin",
            "audio/x-realaudio",
            "audio/x-scpls",
            "audio/x-sd2",
            "audio/x-wav",
            "chemical/x-pdb",
            "chemical/x-xyz",
            "image/bmp",
            "image/cgm",
            "image/cgmComputerGraphicsMetafile",
            "image/g3fax",
            "image/gif",
            "image/ief",
            "image/iefImageExchangeFormat",
            "image/jpeg",
            "image/naplps",
            "image/pcx",
            "image/png",
            "image/prs.btif",
            "image/prs.pti",
            "image/svg+xml",
            "image/tiff",
            "image/tiffTagImageFileFormat",
            "image/vnd.cns.inf2",
            "image/vnd.dwg",
            "image/vnd.dxf",
            "image/vnd.fastbidsheet",
            "image/vnd.fpx",
            "image/vnd.fst",
            "image/vnd.fujixerox.edmics-mmr",
            "image/vnd.fujixerox.edmics-rlc",
            "image/vnd.mix",
            "image/vnd.net-fpx",
            "image/vnd.svf",
            "image/vnd.wap.wbmp",
            "image/vnd.xiff",
            "image/x-cmu-raster",
            "image/x-coreldraw",
            "image/x-coreldrawpattern",
            "image/x-coreldrawtemplate",
            "image/x-corelphotopaint",
            "image/x-djvu",
            "image/x-jg",
            "image/x-jng",
            "image/x-ms-bmp",
            "image/x-photoshop",
            "image/x-portable-anymap",
            "image/x-portable-bitmap",
            "image/x-portable-graymap",
            "image/x-portable-pixmap",
            "image/x-rgb",
            "image/x-xbitmap",
            "image/x-xpixmap",
            "image/x-xwindowdump",
            "inode/blockdevice",
            "inode/chardevice",
            "inode/directory",
            "inode/directory-locked",
            "inode/fifo",
            "inode/socket",
            "message/delivery-status",
            "message/disposition-notification",
            "message/external-body",
            "message/http",
            "message/news",
            "message/partial",
            "message/rfc822",
            "message/s-http",
            "model/iges",
            "model/mesh",
            "model/vnd.dwf",
            "model/vnd.flatland.3dml",
            "model/vnd.gdl",
            "model/vnd.gs-gdl",
            "model/vnd.gtw",
            "model/vnd.mts",
            "model/vnd.parasolid.transmit.binary",
            "model/vnd.parasolid.transmit.text",
            "model/vnd.vtu",
            "model/vrml",
            "multipart/alternative",
            "multipart/appledouble",
            "multipart/byteranges",
            "multipart/digest",
            "multipart/encrypted",
            "multipart/form-data",
            "multipart/header-set",
            "multipart/mixed",
            "multipart/parallel",
            "multipart/related",
            "multipart/report",
            "multipart/signed",
            "multipart/voice-message",
            "text/calendar",
            "text/comma-separated-values",
            "text/css",
            "text/directory",
            "text/english",
            "text/enriched",
            "text/h323",
            "text/html",
            "text/iuls",
            "text/mathml",
            "text/parityfec",
            "text/plain",
            "text/prs.lines.tag",
            "text/rfc822-headers",
            "text/richtext",
            "text/rtf",
            "text/scriptlet",
            "text/sgml",
            "text/t140",
            "text/tab-separated-values",
            "text/texmacs",
            "text/uri-list",
            "text/vnd.abc",
            "text/vnd.curl",
            "text/vnd.DMClientScript",
            "text/vnd.flatland.3dml",
            "text/vnd.fly",
            "text/vnd.fmi.flexstor",
            "text/vnd.in3d.3dml",
            "text/vnd.in3d.spot",
            "text/vnd.IPTC.NewsML",
            "text/vnd.IPTC.NITF",
            "text/vnd.latex-z",
            "text/vnd.motorola.reflex",
            "text/vnd.ms-mediapackage",
            "text/vnd.wap.si",
            "text/vnd.wap.sl",
            "text/vnd.wap.wml",
            "text/vnd.wap.wmlscript",
            "text/x-chdr",
            "text/x-c++hdr",
            "text/x-crontab",
            "text/x-csh",
            "text/x-csrc",
            "text/x-c++src",
            "text/x-java",
            "text/x-makefile",
            "text/xml",
            "text/xml-external-parsed-entity",
            "text/x-moc",
            "text/x-pascal",
            "text/x-server-parsed-html",
            "text/x-setext",
            "text/x-sh",
            "text/x-tcl",
            "text/x-tex",
            "text/x-vcalendar",
            "text/x-vcard",
            "video/dl",
            "video/fli",
            "video/gl",
            "video/mp4v-es",
            "video/MP4V-ES",
            "video/mpeg",
            "video/parityfec",
            "video/pointer",
            "video/quicktime",
            "video/vnd.fvt",
            "video/vnd.motorola.video",
            "video/vnd.motorola.videop",
            "video/vnd.mpegurl",
            "video/vnd.mts",
            "video/vnd.nokia.interleaved-multimedia",
            "video/vnd.vivo",
            "video/x-dv",
            "video/x-la-asf",
            "video/x-mng",
            "video/x-ms-asf",
            "video/x-msvideo",
            "video/x-ms-wm",
            "video/x-ms-wmv",
            "video/x-ms-wmx",
            "video/x-ms-wvx",
            "video/x-sgi-movie",
            "x-conference/x-cooltalk",
            "x-world/x-vrml"
    };


    private List<String> langNameList = new ArrayList<String>(Arrays.asList(langNames));
    private List<String> langCodeList = new ArrayList<String>(Arrays.asList(langCodes));
    private List<String> mimeTypeList = new ArrayList<String>(Arrays.asList(mimeTypes));


    public String[] getLangNames() {
        return langNames;
    }

    public String[] getLangCodes() {
        return langCodes;
    }

    public String[] getMimeTypes() {
        return mimeTypes;
    }

    public List<String> getLangNameList() {
        return langNameList;
    }

    public List<String> getLangCodeList() {
        return langCodeList;
    }

    public List<String> getMimeTypeList() {
        return mimeTypeList;
    }
}
